### PR TITLE
Use es5 var instead of const

### PR DESCRIPTION
**Pull request by AlexBazer**
I think i should be connected to this merge request https://github.com/react-icons/react-icons/pull/187

### CODE REVIEW

**Comment by kamijin-fanta** [comment]
@AlexBazer This file is used for building. Not used in browser. So I think it don't needs to be fixed.

**Comment by AlexBazer** [comment]
@kamijin-fanta  webpack won't compile without this staff fixed
https://github.com/react-icons/react-icons/pull/187#issuecomment-505830954

**Comment by kamijin-fanta** [comment]
I think there's something wrong with this file included in the Webpack build.

**Comment by kamijin-fanta** [comment]
This file is used by the build process and is not imported by the user.

**Pull request closed without merging**
