### PR TITLE
new design

### PR DESCRIPTION
**Pull request by kamijin-fanta**
## Detail

- [x] support esmodules & change import style
- [x] global icon configure with context API
- [x] supports webpack optimization (speed up for build)
- [x] typescript native support
- [x] use gitsubmodules (easier update)
- [x] use yarn (easily to test by managing all related package in yarn workspace)
- [x] new icon set
  - feathericons
- [x] upgrade icon
  - fontawesome5
- [x] configure travis ci & deploy preview site to netlify
  - example preview: http://5b1f83e81f12b742d62c8aca.react-icons.netlify.com

### new import / configure style

```jsx
import React from "react";

import { IconContext } from "react-icons";
import { FaFolder } from "react-icons/lib/fa";
import { MdAccessibility } from "react-icons/lib/md";

funciton App () {
  return (
    <IconContext.Provider value={{ color: "#333" }}>
      <div>
        <MdAccessibility />
        <FaFolder />
      </div>
    </IconContext.Provider>
  );
}
```

### build speed/size improvement!

Use one icon from each of fa and md.
**SIZE: -84% BUILD TIME: -40%**

before:
```
File sizes after gzip:

  244.25 KB  build\static\js\main.2f2e05e7.js
  299 B      build\static\css\main.c17080f1.css
Done in 19.83s.
```

after:
```
File sizes after gzip:

  38.75 KB  build\static\js\main.cc198299.js
  299 B     build\static\css\main.c17080f1.css

Done in 11.79s.
```

## Todo
- [x] add license
- [x] fix README
- [x] update preview site

## I want a vote on this PR

👍 / 👎

### CODE REVIEW

**Comment by JeffersonFilho** [comment]
It looks good to me! When I have a spare time I will test it!

**Comment by AddShoppersJason** [comment]
Looks great! I'll test it out tonight.

**Comment by kamijin-fanta** [comment]
@antoinerousseau @JeffersonFilho @jayehmke  The work is completed. I want you to review it.

**Comment by antoinerousseau** [comment]
thanks @kamijin-fanta for this great work!

- are submodules really the best solution over npm dependencies?
- any way we could import from `react-icons/fa` instead of `react-icons/lib/fa` to be even more simple?
- is it possible to not use the context api to set an icon's color for example?

**Comment by kamijin-fanta** [comment]
@antoinerousseau Thank you for review!

- If sgv is available, it is using npm. If can not use npm using gitsubmodules.
  -  see: https://github.com/react-icons/react-icons/blob/feat/new-design/packages/react-icons/src/icons/index.js
- I preferred compatibility and kept the path. I also think that `react-icons/fa` is better, but I do not know I can change it...
- I forgot the implementation. Thank you!  example: `<FaFolder color ="red" />`

**Comment by kamijin-fanta** [comment]
If there is no response for a while, I will merge without approve!

**Comment by JeffersonFilho** [comment]
Sorry I have been extremely bush recently! I will see if I can test it today/tomorrow!

**Comment by kamijin-fanta** [comment]
@gorangajic I want to verify this branch. so, I want to release beta. What should I do?

**Comment by kumarharsh** [comment]
@kamijin-fanta would it be possible to specify the class for an icon? like:

```
<FaFolder className="folder" />; // usual classnames being applied
// and
<FaFolder className={css.folder} />; // css-modules style local imports
```

**Comment by kamijin-fanta** [comment]
@kumarharsh Thank you!
I forgot to support additional attributes, so added it now

```jsx
<FaFolder color="red" className="additional-class-name" />
```

image

**Comment by kumarharsh** [comment]
Hi @kamijin-fanta. Thanks for the awesome work in moving the project forward 👍

Is there a reason to expose color as an attribute on the context provider? Because we can already color individual icons using `className` or `style` or the icon gets the current font color of its parent anyways.

**Comment by kamijin-fanta** [comment]
@kumarharsh Maintains the currently supported functions as much as possible. I think that it is not a function causing trouble.  specify undefined for color, the style property is empty.

**Comment by kumarharsh** [comment]
Okay. Thanks for the clarification.

**Comment by kamijin-fanta** [comment]
@gorangajic  Please give me the publishing authority https://www.npmjs.com/~kamijin_fanta

**Comment by gorangajic** [comment]
Sorry I have missed that notification. I will give you access right now

**Comment by kamijin-fanta** [comment]
thanks!!!

`react-icons@3.0.0-beta.1` released! Please install it into the project and try it out.

```
$ npm install react-icons@next
```

- document(include migration gude): https://github.com/react-icons/react-icons/blob/feat/new-design/README.md
- preview site: https://react-icons.netlify.com/

**Comment by kamijin-fanta** [comment]
tested in my company's TypeScript project. I will release 3.0.0 soon.

**Comment by kamijin-fanta** [comment]
published

**Pull request merged**
