### PR TITLE
Proposed for Webfont Medical Icon

### PR DESCRIPTION
**Pull request by mdestafadilah**

### CODE REVIEW

**Comment by kamijin-fanta** [comment]
@mdestafadilah Thank you for your contribution! This project uses yarn. Please fix it.

**Comment by mdestafadilah** [comment]
I'll merge again, omg ... until 2 years ... i'm not focused.

**Comment by mdestafadilah** [comment]
Hi @kamijin-fanta i'm remove npm, and using yarn. sorry.

**Comment by mdestafadilah** [comment]
Relate here  #434

**Pull request closed without merging**
