### PR TITLE
Fixed search focus issue on reload

### PR DESCRIPTION
**Pull request by Yash-Shukla-9**
- Fixed page reload input focus issue
react-icon

### CODE REVIEW

**Comment by Yash-Shukla-9** [comment]
Hello @kamijin-fanta , can you please look into this Pr.

**Comment by kamijin-fanta** [comment]
Thanks for the report. I have created a new PR as this appears to be a problem that should be resolved using Astro's functionality.

**Comment by Yash-Shukla-9** [comment]
Hello @kamijin-fanta,  Thank You for Acknowledge my Suggestion. I will also look into your updated changes.

**Comment by kamijin-fanta** [comment]
Another way it was resolved, thanks for submitting the PR.

**Pull request closed without merging**
