### PR TITLE
FEAT: Icon parent wrapper element/component

### PR DESCRIPTION
**Pull request by bombillazo**
Resolves https://github.com/react-icons/react-icons/issues/719

- Add a feature to auto-wrap icons in a span component with a class name

### CODE REVIEW

**Comment by bombillazo** [comment]
Hey @kamijin-fanta , anyone could take a look at this PR?

**Comment by bombillazo** [comment]
Any takers? @kamijin-fanta  @gorangajic @nolanleung

**Comment by kamijin-fanta** [comment]
It is unclear if a merge should be performed because the use case is not known. You could write code `<span className="wrapper"><FaSearch /></span>`. You can also define such a wrapper component.

**Comment by bombillazo** [comment]
Hey, imagine the case where we wish to apply a custom styling/wrapper to every icon class we import to control their global behavior. How would one currently apply such a wrapper to **_all_** icons? Must one create the custom class or wrapper component on every icon instance component used in the code? 

That is what this PR tries to address, by incorporating the logic into the icons and context one can globally control the icons.

**Comment by kamijin-fanta** [comment]
There is still the ability to globally assign class names. Whether it is necessary to wrap components depends on the situation in which they will be used. I would like to know in what cases it is necessary to wrap repeatedly.

**Comment by bombillazo** [comment]
We want to add a global class to any and to all react icons we import from `react-icon`. Imagine I use the `<FaSearch />` icon in 5 different components. We would need to update every single <FaSearch /> usage to add a global class. And that is just 1 icon; we are using dozens of icons in different components and layouts.

**Comment by kamijin-fanta** [comment]
Think of it as difficult to add features that are not used very often. If such UI frameworks are used a lot in the React community, I would welcome them. However, when merging, the API should accept generic React components, not just span.

**Comment by bombillazo** [comment]
Hey @kamijin-fanta, I updated the functionality; please review it to see if it looks better.

**Comment by bombillazo** [comment]
Hey @kamijin-fanta , the new implementation aligns to using generic React components rather than hardcode the wrapper to span.

**Comment by bombillazo** [comment]
I've tested this out and so far haven't had any issues, Im using patch-package though.

**Comment by bombillazo** [comment]
Hey @kamijin-fanta , any feedback?

**Comment by bombillazo** [comment]
Hey @kamijin-fanta , any update on if this feature can be merged?

**Comment by kamijin-fanta** [comment]
If anyone else needs it, please let me know the use case. I will not add a feature that only one person needs.

**Comment by bombillazo** [comment]
Fair enough, I'll leave it open in case, we've made it work for use using `patch-package` and it is working perfectly so far.

**Comment by bombillazo** [comment]
We're no longer needing this logic, and after no activity, I'm OK closing this PR, perhaps in the future there is a usecase for this.

**Pull request closed without merging**
