### PR TITLE
Update RemixIcon to 2.5.0 & Add the Fill icons

### PR DESCRIPTION
**Pull request by vishalkdotcom**
Fixes: #308

- Update RemixIcon to 2.5.0
- Add the `Fill` icons

### CODE REVIEW

**Comment by vishalkdotcom** [comment]
@kamijin-fanta Can you please review this PR?
Please let me know, anything else required that I have missed.

Thanks!

**Comment by GeorgeNance** [comment]
@kamijin-fanta hate to ping you again, but could you check this out ? I really need the fill versions of remix icons.

**Comment by ghndr** [comment]
I'm facing the issue as well, need the fill icons of the remix icon pack.

**Comment by coreyward** [comment]
+1 here — Maybe some additional volunteer maintainers can be added to accept PRs like this? Otherwise someone has to fork the project entirely and release on NPM under a new name in order to use this.

Paging @kamijin-fanta @gorangajic @jayehmke @JeffersonFilho

**Comment by aliogaili** [comment]
I prefer more maintainers on this project those PRs are not that hard to merge, but I've already forked it and released it with this PR (among other changes).

You can check the updated review site [here](https://icons.meronex.com/) and the npm package [here](https://www.npmjs.com/package/@meronex/icons).

I hope that helps.

**Comment by coreyward** [comment]
@aliogaili Wish I had seen that sooner, [I did the same](https://github.com/coreyward/react-icons/). 😅🤦‍♂️

**Comment by kamijin-fanta** [comment]
thank you for contribute! published in 3.11.0. try it!

**Pull request merged**
