### PR TITLE
Add Heroicons 2

### PR DESCRIPTION
**Pull request by bacali95**
This MR adds support for HeroIcons version 2.0.8, @nolanleung can you please take a look? thanks :smile:

### CODE REVIEW

**Review by nolanleung — APPROVED** [review]
awesome!

**Comment by corysimmons** [comment]
@bacali95 @nolanleung Does this include the mini sizes?

**Comment by bacali95** [comment]
> @bacali95 @nolanleung Does this include the mini sizes?

No it doesn't, since the mini icons are the same solid ones but smaller I thought maybe using the size prop wee can achieve the same result

**Comment by corysimmons** [comment]
It doesn't look like they're identical-identical. Notice the top of the box not being rounded anymore.

Solid (24x24):
image

Mini (20x20):
image

I think the imports should be:
- `import {Hi2Xyz} from 'react-icons/hi2/outline`
- `import {Hi2Xyz} from 'react-icons/hi2/solid`
- `import {Hi2Xyz} from 'react-icons/hi2/mini`

**Comment by bacali95** [comment]
That is indeed correct, they don't look the same, I will open a PR later on to add the mini imports..

**Comment by Cody-W-Tucker** [comment]
I keep getting an import error, has something changed?

`Module not found: Can't resolve 'react-icons/hi2'
  4 | import { HiHome, HiOutlineCurrencyDollar, HiX } from 'react-icons/hi'
> 5 | import { HiBars3, HiXMark } from 'react-icons/hi2'`

**Comment by corysimmons** [comment]
@Cody-W-Tucker It hasn't been published to npm yet.

**Pull request merged**
