### PR TITLE
Add Lucide icons

### PR DESCRIPTION
**Pull request by bai**
Add Lucide icons, updated version of https://github.com/react-icons/react-icons/pull/602.

@kamijin-fanta I pushed an updated version of [an older PR](https://github.com/react-icons/react-icons/pull/602) which hopefully unblocks getting this shipped. Adding these will make a whole bunch of folks' life easier 🙏🏼 ❤️

### CODE REVIEW

**Comment by PeerRich** [comment]
yes!! that would be lovely

**Comment by jonathanwilke** [comment]
I need this!

**Comment by bai** [comment]
Actual footage of me when this PR gets merged:

https://user-images.githubusercontent.com/17348/227532391-67b44999-8421-41db-811d-c429b9624621.mp4

**Comment by PeerRich** [comment]
i dont think its gonna happen anymore

**Review by PeerRich — APPROVED** [review]

**Comment by bai** [comment]
👋🏼 @kamijin-fanta Apologies for being a pain in the arse, just wanted to see if this is something you could consider merging? 🙏🏼

**Comment by harisvsulaiman** [comment]
@bai Can anyone consider publishing this under different namespace.

**Comment by abhi1693** [comment]
@harisvsulaiman I forked this library under a new name at https://github.com/Onemind-Services-LLC/react-icons-ng. I'll also try to get most of the pending PRs included in the next release

**Comment by bai** [comment]
Thanks @abhi1693 - on a personal note, it's unfortunate that there seem to be no feedback at all - here and on other Pull Requests. Of course, this is an OSS library and sure thing I get that the maintainer is not obligated at all to even look in here. 

However (and I'm saying this in good faith, not with frustration or anything!) I wish there was at least some feedback in 2+ months passed since creating this PR and 8 months since the original https://github.com/react-icons/react-icons/pull/602. Something to give us closure would suffice, even saying that we shouldn't expect things to move so we could move on ❤️‍🩹

**Comment by weilueluo** [comment]
would love to see this gets merged 👍

**Comment by nolanleung** [comment]
🚀

**Pull request merged**
