### PR TITLE
adding support for material design symbols

### PR DESCRIPTION
**Pull request by nicksrandall**
In April 2022, Google released a new version of "material design icons" called "material design symbols" which come in 3 variants (Sharp, Rounded, and Outlined). This PR adds support for this new set of icons.

Note: This change also bumps Material Icons package to latest version.

Also, not 100% sure but this *might* superseed #408

### CODE REVIEW

**Comment by nicksrandall** [comment]
@kamijin-fanta I have rebased this PR to work with all your latest changes. I *think* it is ready to go.

**Comment by nicksrandall** [comment]
@kamijin-fanta This has been rebased again and bumped to the latest version of Material Design Icons. I *should* be ready to go.

**Comment by user72356** [comment]
This is a very nice PR and I'm disappointed it's being ignored.

**Comment by nicksrandall** [comment]
@kamijin-fanta anything I can do to assist this in getting reviewed and/or merged? Do you have any concerns with this implementation?

**Comment by nicksrandall** [comment]
@kamijin-fanta Any chance this can be merged?

**Comment by nicksrandall** [comment]
I have fixed the merge conflicts. I would really like to see this land.

**Comment by mike-shtil** [comment]
@kamijin-fanta this very useful PR seems to have been ignored for many months now. Is there anything the community here can do to help with the review?

**Comment by bring-shrubbery** [comment]
@kamijin-fanta We need this very much. Is there any way we can make it easier to merge this PR?

**Comment by mike-shtil** [comment]
@nicksrandall this is shaping up to be the replacement fork for this project, https://github.com/Onemind-Services-LLC/react-icons-ng

He's already pulled/replicated many of the awaiting changes here but not yet this PR. Would you mind opening it there?

P.S I see there's "Material Design icons 2" added in `react-icons-ng` but the icon set isn't MDS.

**Comment by chiyu144** [comment]
The merge of this PR would be very nice and very useful to our team (a lot of UI / UX designers were already migrated to "Symbols" now), I wonder why this PR is being ignored for so long?

**Review by nolanleung — APPROVED** [review]

**Comment by nolanleung** [comment]
🚀

**Comment by kamijin-fanta** [comment]
This commit may have significantly increased build time. There is also the possibility of revert.

**Comment by kamijin-fanta** [comment]
Different alternative methods of implementation were used. I want you to try it.

**Comment by mike-shtil-loop** [comment]
Ultimately a glyph is a glyph. @kamijin-fanta is this alternative approach acceptable in terms of build time? Anything we could do to assist - say fix conflicts?
Material Design Symbols is quite an anticipated feature and any solution would be appreciated.

**Pull request merged**
