### PR TITLE
⚡️ Added support to copy to clipboard svg, icon name and icon import path

### PR DESCRIPTION
**Pull request by mzohaibqc**
React icons is an awesome project but it does not provide functionality to copy svg string which can be used anywhere that is possible with https://heroicons.com. 

I added support to copy 
 - SVG
 - Icon Name
 - Icon import path

by hovering over the icon box in search results.

Demo: https://competent-kilby-fff24a.netlify.app/search?q=home

image

And on hover

image

### CODE REVIEW

**Review by 3imed-jaberi — APPROVED** [review]
LGTM +1

**Comment by 0x0a0d** [comment]
please merge this

**Comment by mzohaibqc** [comment]
I can merge this even after approval from @3imed-jaberi. Can someone merge this.

**Comment by RickeyWard** [comment]
BUMP, can we get this merged?

**Comment by i-am-the-slime** [comment]
@mzohaibqc Any chance you could host this on vercel or something yourself?

**Comment by mzohaibqc** [comment]
> @mzohaibqc Any chance you could host this on vercel or something yourself?

I can do that but that will not help since no one would know that. At the moment, you can still see the change in url in PR.

**Comment by hugohutri** [comment]
This is precisely what I need :+1: Can this be merged?

**Comment by abhi1693** [comment]
@mzohaibqc Would you consider providing this on a more maintained fork at https://github.com/Onemind-Services-LLC/react-icons-ng?

**Comment by NayamAmarshe** [comment]
Will this ever be merged?

**Comment by iMykhailychenko** [comment]
the library is great, but the idea of copying just the name is terrible (IMO). Why hasn't this PR been merged yet?

**Comment by kamijin-fanta** [comment]
Thank you for your contribution. This is now implemented. Copying of SVG strings is not currently supported, but will be added if needed.

**Comment by NayamAmarshe** [comment]
> Thank you for your contribution. This is now implemented. Copying of SVG strings is not currently supported, but will be added if needed.

Thank you for the fantastic work @kamijin-fanta

**Pull request closed without merging**
