### PR TITLE
starting change project struct

### PR DESCRIPTION
**Pull request by kamijin-fanta**
## Changes

- Publishing multiple packages with different structures
  - `react-icons` : this is a general package. multiple icons are recorded in one file.
  - `@react-icons/all-files` : this package to use when there is a problem with optimization. one icon is recorded in one file.
- Build process refactoring
  - split into multiple files
  - save build artifacts under `packages/` to build multiple packages with different structures
  - report the elapsed time for each build step and number of icons for each icon style
  - use yarn 2
  - execute tcs babel in nodejs childprocess
  - remove package dependencies that are not used now
  - eslint upgrade to 7
  - upgrade nextjs and rewrite `next.config.js`
- Add test
  - react project using new package `@react-icons/all-files`

## Which package should I choose?

the same icon is included in the two packages.

### `react-icons`

this is a general package. Suitable for CreateReactApp, Webpack, npm, yarn, etc.

It reduces the number of files and shortens the time of `npm install` `yarn install`.

### `@react-icons/all-files`

use this if you have problems with the `react-icons` package.
solves the problem of large build artifacts in some bundlers.
suitable for MeteorJS etc.

It takes a long time to install the package because it contains many files (about 50k).

### CODE REVIEW

**Comment by kamijin-fanta** [comment]
we can try the pre-release here: https://github.com/react-icons/react-icons/releases/tag/3.11.1-snapshot.0

**Comment by wardpeet** [comment]
I've been testing this pr on https://www.gatsbyjs.com with great success. Would love to get this on the stable channel.

**Comment by kamijin-fanta** [comment]
@wardpeet Thanks for your feedback!! I will release this.

**Comment by kamijin-fanta** [comment]
It has been published: https://github.com/react-icons/react-icons/releases/tag/v4.0.0

**Pull request merged**
