### PR TITLE
Upgrade dependencies, consistent prettier/linting, fix warnings

### PR DESCRIPTION
**Pull request by wescarr**
Hey react-icons folks, I originally set out to fix a perf issue: https://github.com/react-icons/react-icons/issues/575
But in the process of setting my local environment ran into a few issues with outdated and deprecated packages, so I set about upgrading mostly the preview package, but also a few top level changes.

I tested the preview site as best I could with proposed changes, and made sure the rest of the contributing setup also still works. I also ran the tests in the other packages.

Summary of changes:
- Upgrade to Yarn 3
- Upgrade dart as node-dart is deprecated
- Upgrade to latest version of next, next-pwa, react, typescript for preview site
- Fix numerous lint and ts warnings/errors.
- Add a more appropriate eslint config for preview package based of next
- Remove unnecessary import of React in preview package
- Remove unused build-state.yml as it's been replaced by install-state
- Run build scripts to update package version

Looking forward to your feedback.

### CODE REVIEW

**Comment by wescarr** [comment]
@kamijin-fanta I deployed a preview of my changes to vercel here: https://react-icons-j5yn610k4-wescarr.vercel.app

**Comment by wescarr** [comment]
Here's a link to an evergreen version of my changes: https://react-icons-git-deps-major-updates-wescarr.vercel.app
I'll note that the dependency updates also make search much faster so I would feel good about closing out #575 if this lands.

**Comment by wescarr** [comment]
@kamijin-fanta Any chance you will be able to review this soon? Thanks!

**Comment by kamijin-fanta** [comment]
Thank you for your contribution. However, the Next.js implementation has been removed from the repository and is closed.

**Pull request closed without merging**
